apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fib-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: fib-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
