apiVersion: apps/v1
kind: Deployment
metadata:
  name: app 
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app 
    spec:
      containers:
      - name: app
        image: redis-session-app:v1 
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-svc:6379"
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app
  ports:
  - name: app-svc
    port: 3000
    targetPort: 3000
---

