apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-test-deployment
  labels:
    app: dns-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns-test
  template:
    metadata:
      labels:
        app: dns-test
    spec:
      containers:
        - name: dns-test
          image: 10.0.0.220:35000/dns-test:v0.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dns-test-service
spec:
  selector:
    app.kubernetes.io/name: dns-test
  ports:
    - protocol: TCP
      port: 3123
      targetPort: 3000